title: "La Cuisine de Maman"
description: "Des recettes faites avec amour, transmises de génération en génération."
baseurl: "/recette_maman"
url: "https://freaky2112.github.io"

author:
  name: "Maman"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /recettes/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Catégories
category_list:
  - Petit-déjeuner
  - Soupes & Mijotés
  - Plats principaux
  - Accompagnements
  - Desserts
  - Pâtisserie
  - Boissons
